apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: todo-k8s
spec:
  template:
    spec:
      containers:
        - name: todolist
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 512Mi
