apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: todo-k8s
spec:
  template:
    spec:
      containers:
        - name: todolist

          livenessProbe:
            httpGet:
              path: /livez
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /readyz
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
