apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  template:
    spec:
      containers:
        - name: mariadb
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
