apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.36
          command: ["sh", "-c", "echo 'Waiting for MariaDB to be ready...'; until nc -z localhost 3306; do sleep 2; done; echo 'MariaDB is ready'"]
      containers:
        - name: mariadb
          image: mariadb:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: todolist-config
                  key: MYSQL_DB
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todolist-secret
                  key: MYSQL_ROOT_PASSWORD
