apiVersion: v1
kind: Service
metadata:
  name: {{ include "todolist-chart.fullname" . }}-api
spec:
  type: ClusterIP
  selector:
    app: {{ include "todolist-chart.fullname" . }}-api
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
      protocol: TCP

