apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "todolist-chart.backendName" . }}
spec:
  serviceName: {{ include "todolist-chart.backendHeadlessName" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "todolist-chart.backendName" . }}
  template:
    metadata:
      labels:
        app: {{ include "todolist-chart.backendName" . }}
    spec:
      containers:
        - name: mariadb
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.service.port }}
{{ if .Values.backend.probes.readiness.enabled }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.backend.probes.readiness.port }}
            initialDelaySeconds: {{ .Values.backend.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.backend.probes.readiness.failureThreshold }}
{{ end }}
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.db }}

            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.mysql.name }}
                  key: MYSQL_ROOT_PASSWORD
          
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql

  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
            