apiVersion: v1
kind: Service
metadata:
  name: {{ include "todolist-chart.frontendName" . }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
  selector:
    app: {{ include "todolist-chart.frontendName" . }}
